name: enzomir
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  gap: ^3.0.1
  curved_labeled_navigation_bar: ^2.0.6
  go_router: ^15.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/onboarding/image.png
    - assets/images/onboarding/get_started_top_image.png
    - assets/icons/Google.png
    - assets/images/onboarding/party_image.png
    - assets/icons/bottom_nav/home.png
    - assets/icons/bottom_nav/customer.png
    - assets/icons/bottom_nav/calendar.png
    - assets/icons/bottom_nav/chat_bubble.png
    - assets/icons/bottom_nav/add.png
    - assets/icons/bottom_nav/Search.png
    - assets/images/home/app_bar.png
    - assets/images/home/recomended_for_you.png
    - assets/images/events/event1.png
    - assets/images/events/event2.png
    - assets/images/auth/login_appbar2.png
    - assets/icons/auth/social_media/X.png
    - assets/icons/auth/social_media/google.png
      # - assets/images/onboarding/get_started_top_image2.png


  fonts:
    - family: Jomolhari
      fonts:
        - asset: assets/fonts/Jomolhari-Regular.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-SemiBold.otf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
    - family: Airbnb
      fonts:
        - asset: assets/fonts/AirbnbCereal_W_300.otf
          weight: 300
        - asset: assets/fonts/AirbnbCereal_W_400.otf
          weight: 400
        - asset: assets/fonts/AirbnbCereal_W_500.otf
          weight: 500
        - asset: assets/fonts/AirbnbCereal_W_700.otf
          weight: 700
        - asset: assets/fonts/AirbnbCereal_W_800.otf
          weight: 800
        - asset: assets/fonts/AirbnbCereal_W_900.otf
          weight: 900