// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR1mh0fjfMhJ5n0mCTJhXOlI9yJ4yfqz4',
    appId: '1:954242563166:web:db46d4930b0858eeda48cf',
    messagingSenderId: '954242563166',
    projectId: 'enzomir-c32b8',
    authDomain: 'enzomir-c32b8.firebaseapp.com',
    storageBucket: 'enzomir-c32b8.firebasestorage.app',
    measurementId: 'G-LMH84VWT3R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXlWrO0Wxx_6uarr6wMRN1hHzvWVL6dAY',
    appId: '1:954242563166:android:531f2ef979ddbdf6da48cf',
    messagingSenderId: '954242563166',
    projectId: 'enzomir-c32b8',
    storageBucket: 'enzomir-c32b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL8c9V9ACf1Pumt-z5KIh1yKoKXz9_xSM',
    appId: '1:954242563166:ios:9d76f7fd2e555094da48cf',
    messagingSenderId: '954242563166',
    projectId: 'enzomir-c32b8',
    storageBucket: 'enzomir-c32b8.firebasestorage.app',
    iosBundleId: 'com.example.enzomir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL8c9V9ACf1Pumt-z5KIh1yKoKXz9_xSM',
    appId: '1:954242563166:ios:9d76f7fd2e555094da48cf',
    messagingSenderId: '954242563166',
    projectId: 'enzomir-c32b8',
    storageBucket: 'enzomir-c32b8.firebasestorage.app',
    iosBundleId: 'com.example.enzomir',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR1mh0fjfMhJ5n0mCTJhXOlI9yJ4yfqz4',
    appId: '1:954242563166:web:aba6810d5a2860d2da48cf',
    messagingSenderId: '954242563166',
    projectId: 'enzomir-c32b8',
    authDomain: 'enzomir-c32b8.firebaseapp.com',
    storageBucket: 'enzomir-c32b8.firebasestorage.app',
    measurementId: 'G-GB7X9PBTEE',
  );
}
